variant: flatcar
version: 1.1.0
ignition:
  config:
    merge:
      - local: out/flatcar_base.json

systemd:
  units:
    - name: init_harbor.service
      enabled: true
      contents: |
        [Unit]
        Description=Install Harbor
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service

        [Service]
        Type=oneshot
        RemainAfterExit=true
        WorkingDirectory=/home/flatcar
        User=flatcar
        Group=flatcar
        ExecStartPre=-/usr/bin/mkdir /home/flatcar/.harbor/harbor_installer
        ExecStartPre=-/usr/bin/tar xzvf /home/flatcar/.harbor/harbor-online-installer.tgz -C /home/flatcar/.harbor/harbor_installer --strip-components 1
        ExecStart=/usr/bin/cp /home/flatcar/.harbor/harbor.yml /home/flatcar/.harbor/harbor_installer/harbor.yml

        [Install]
        WantedBy=multi-user.target

storage:
  directories:
    - path: /home/flatcar/.harbor
      user: { name: flatcar }
      group: { name: flatcar }
    - path: /home/flatcar/.harbor/certs
      overwrite: false
      user: { name: flatcar }
      group: { name: flatcar }
    - path: /home/flatcar/.harbor/data
      overwrite: false
      user: { id: 10000 }
      group: { id: 10000 }
    - path: /home/flatcar/.harbor/data/secret/core
      overwrite: false
      user: { id: 10000 }
      group: { id: 10000 }
    - path: /home/flatcar/.harbor/data/secret/registry
      overwrite: false
      user: { id: 10000 }
      group: { id: 10000 }
    - path: /home/flatcar/.harbor/data/secret/cert
      overwrite: false
      user: { id: 10000 }
      group: { id: 10000 }
    - path: /home/flatcar/.harbor/data/secret/keys/secretkey
      overwrite: false
      user: { id: 10000 }
      group: { id: 10000 }
    - path: /home/flatcar/.harbor/data/job_logs
      user: { id: 10000 }
      group: { id: 10000 }
    - path: /home/flatcar/.harbor/data/registry
      overwrite: false
      user: { id: 10000 }
      group: { id: 10000 }
      mode: 0700
    - path: /home/flatcar/.harbor/data/database/pg15
      overwrite: false
      user: { id: 999 }
      group: { id: 999 }
    - path: /home/flatcar/.harbor/data/redis
      overwrite: false
      user: { id: 999 }
      group: { id: 999 }
    - path: /etc/docker/certs.d/harbor.honeblog.com
      overwrite: false
      user: { name: root }
      group: { name: root }
  files:
    - path: /etc/systemd/network/static.network
      contents:
        inline: |
          [Match]
          Name=eth0

          [Network]
          Address=172.20.5.2/16
          Gateway=172.20.0.1
          NTP=172.20.0.1
    - path: /etc/hostname
      contents:
        inline: git.peach-ktq.dev
