variant: flatcar
version: 1.1.0
ignition:
  config:
    merge:
      - local: out/flatcar_base.json
passwd:
  users:
    - name: gitea
      groups: [docker]
    - name: postgres
      groups: [docker]
systemd:
  units:
    - name: gitea.service
      enabled: true
      contents: |
        [Unit]
        Description=run gitea
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service

        [Service]
        Type=oneshot
        RemainAfterExit=true
        WorkingDirectory=/home/flatcar
        User=gitea
        Group=gitea
        ExecStartPre=-/usr/bin/docker stop gitea
        ExecStartPre=-/usr/bin/docker rm gitea
        ExecStartPre=/usr/bin/docker pull harbor.honeblog.com/others/gitea:latest-rootless
        ExecStart=/usr/bin/docker run --rm --name gitea\
          -v /home/flatcar/.gitea/data:/var/lib/gitea\
          -v /home/flatcar/.gitea/config:/etc/gitea\
          -v /etc/timezone:/etc/timeozone:ro\
          -v /etc/localtime:/etc/localtime:ro\
          -p 3000:3000\
          -p 2222:2222\
          --env-file /home/flatcar/.gitea/.env\
          harbor.honeblog.com/others/gitea:latest-rootless

        [Install]
        WantedBy=multi-user.target
    - name: gitea-postgres.service
      enabled: true
      contents: |
        [Unit]
        Description=run postgres
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service

        [Service]
        Type=oneshot
        RemainAfterExit=true
        WorkingDirectory=/home/flatcar
        User=postgres
        Group=postgress
        ExecStartPre=-/usr/bin/docker stop gitea-postgress
        ExecStartPre=-/usr/bin/docker rm gitea-postgress
        ExecStartPre=/usr/bin/docker pull harbor.honeblog.com/database/postgress
        ExecStart=/usr/bin/docker run --rm --name gitea-postgress\
          -v /home/flatcar/.gitea-postgress/data:/var/lib/postgresql/data\
          -p 5432:5432\
          --env-file /home/flatcar/.postgress/.env\
          harbor.honeblog.com/database/postgress:latest

        [Install]
        WantedBy=multi-user.target
storage:
  directories:
    - path: /home/flatcar/.gitea/data
      user: { name: gitea }
      group: { name: gitea }
    - path: /home/flatcar/.gitea/config
      user: { name: gitea }
      group: { name: gitea }
    - path: /home/flatcar/.gitea-postgress/data
      user: { name: postgres }
      group: { name: postgres }
  files:
    - path: /etc/systemd/network/static.network
      contents:
        inline: |
          [Match]
          Name=eth0

          [Network]
          Address=172.20.5.2/16
          Gateway=172.20.0.1
          NTP=172.20.0.1
    - path: /etc/hostname
      contents:
        inline: git.peach-ktq.dev
