http:
  routers:
    dashboard01:
      entryPoints:
        - web-sec-private
      rule: Host(`traefik01.reyokatsu.net`)
      service: api@internal
      tls:
        certResolver: cloudflare
    dashboard02:
      entryPoints:
        - web-sec-private
      rule: Host(`traefik02.reyokatsu.net`)
      service: api@internal
      tls:
        certResolver: cloudflare

    grafana:
      entryPoints:
        - web-sec-private
      rule: Host(`grafana.reyokatsu.net`)
      service: grafana
      tls:
        certResolver: cloudflare
    minio-loki:
      entryPoints:
        - web-sec-private
      rule: Host(`minio-loki.reyokatsu.net`)
      service: minio-loki
      tls:
        certResolver: cloudflare

    git-peach:
      entryPoints:
        - web-sec
      rule: Host(`git.reyokatsu.net`)
      service: git-peach
      tls:
        certResolver: cloudflare

  services:
    grafana:
      loadBalancer:
        servers:
          - url: "http://172.20.5.15:3000"
    minio-loki:
      loadBalancer:
        servers:
          - url: "http://172.20.5.15:9001"
    git-peach:
      loadBalancer:
        servers:
          - url: "http://172.20.20.1:3000"
