http:
  routers:
    dashboard01:
      rule: Host(`traefik01.honeblog.com`)
      service: api@internal
    dashboard02:
      rule: Host(`traefik02.honeblog.com`)
      service: api@internal

    grafana:
      entryPoints:
        - web
      rule: Host(`grafana.honeblog.com`)
      service: grafana
  services:
    grafana:
      loadBalancer:
        servers:
        - url: "http://172.20.5.1:3000"