# !Note: 

http:
  routers:
    dashboard01:
      entryPoints:
        - web-sec-private
      rule: Host(`traefik01.honeblog.com`)
      service: api@internal
      tls:
        certResolver: cloudflare
    dashboard02:
      entryPoints:
        - web-sec-private
      rule: Host(`traefik02.honeblog.com`)
      service: api@internal
      tls:
        certResolver: cloudflare

    grafana:
      entryPoints:
        - web-sec
      rule: Host(`grafana.honeblog.com`)
      service: grafana
      tls:
        certResolver: cloudflare
    minio-loki:
      entryPoints:
        - web-sec-private
      rule: Host(`minio-loki.honeblog.com`)
      service: minio-loki
      tls:
        certResolver: cloudflare

  services:
    grafana:
      loadBalancer:
        servers:
        - url: "http://172.20.5.1:3000"
    minio-loki:
      loadBalancer:
        servers:
        - url: "http://172.20.5.15:9001" 
        