log:
  filePath: "/logs/traefik.log"
  maxSize: 50
  maxBackups: 3

accessLog:
  filePath: "/logs/access.log"
  format: "json"
  bufferingSize: 100

metrics:
  prometheus:
    addEntryPointsLabels: true
    entryPoint: metrics

entryPoints:
  web:
    address: :80
  web-sec:
    address: :443
  metrics:
    address: :8082


api:
  insecure: false
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/external_service.yml

certificatesResolvers:
  cloudflare:
    acme:
      keyType: 'EC384'
      storage: /acme/acme.json
      dnsChallenge:
        provider: cloudflare
      caServer: https://acme-v02.api.letsencrypt.org/directory
      