entryPoints:
  web:
    address: :80
  web-sec:
    address: :443

api:
  insecure: false
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/external_service.yml