log:
  filePath: "/logs/traefik.log"
  maxSize: 50
  maxBackups: 3
  level: DEBUG

accessLog:
  filePath: "/logs/access.log"
  format: "json"
  bufferingSize: 100

metrics:
  prometheus:
    addEntryPointsLabels: true
    entryPoint: metrics

entryPoints:
  web:
    address: :80
  web-sec:
    address: :443
  web-sec-private:
    address: :8443
  metrics:
    address: :8082

api:
  insecure: false
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/external_service.yml

certificatesResolvers:
  cloudflare:
    acme:
      email: test@example.com
      keyType: "EC384"
      storage: /acme/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
      #caServer: https://acme-v02.api.letsencrypt.org/directory
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
