variant: flatcar
version: 1.1.0
ignition:
  config:
    merge:
      - local: out/flatcar_base.json
passwd:
  users:
    - name: forgejo
      uid: 1500
      groups: [docker]
    - name: postgres
      groups: [docker]
    - name: minio
      groups: [docker]
    - name: lldap
      groups: [docker]
systemd:
  units:
    - name: forgejo.service
      enabled: true
      contents: |
        [Unit]
        Description=run forgejo
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service

        [Service]
        Type=oneshot
        RemainAfterExit=true
        WorkingDirectory=/home/flatcar
        User=forgejo
        Group=forgejo
        ExecStartPre=-/usr/bin/docker stop forgejo
        ExecStartPre=-/usr/bin/docker rm forgejo
        ExecStartPre=/usr/bin/docker pull harbor.honeblog.com/others/forgejo:10
        ExecStart=/usr/bin/docker run --rm --name forgejo\
          -v /home/flatcar/.forgejo/data:/data\
          -v /etc/timezone:/etc/timeozone:ro\
          -v /etc/localtime:/etc/localtime:ro\
          -p 3000:3000\
          -p 222:222\
          --env-file /home/flatcar/.forgejo/.env\
          harbor.honeblog.com/others/forgejo:10

        [Install]
        WantedBy=multi-user.target
    - name: postgres-forgejo.service
      enabled: true
      contents: |
        [Unit]
        Description=run postgres
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service

        [Service]
        Type=oneshot
        RemainAfterExit=true
        WorkingDirectory=/home/flatcar
        User=postgres
        Group=postgres
        ExecStartPre=-/usr/bin/docker stop postgres-forgejo
        ExecStartPre=-/usr/bin/docker rm postgres-forgejo
        ExecStartPre=/usr/bin/docker pull harbor.honeblog.com/database/postgres
        ExecStart=/usr/bin/docker run --rm --name postgres-forgejo\
          -v /home/flatcar/.postgres-forgejo/data:/var/lib/postgresql/data\
          -p 5432:5432\
          --env-file /home/flatcar/.postgres-forgejo/.env\
          harbor.honeblog.com/database/postgres:latest
        [Install]
        WantedBy=multi-user.target
    - name: minio-forgejo.service
      enabled: true
      contents: |
        [Unit]
        Description=run minio
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service

        [Service]
        Type=oneshot
        RemainAfterExit=true
        WorkingDirectory=/home/flatcar
        User=minio
        Group=minio
        ExecStartPre=-/usr/bin/docker stop minio-forgejo
        ExecStartPre=-/usr/bin/docker rm minio-forgejo
        ExecStartPre=/usr/bin/docker pull quay.io/minio/minio
        ExecStart=/usr/bin/docker run --name minio-forgejo\
          -p 9000:9000 -p 9001:9001\
          -v /home/flatcar/.minio-forgejo/data:/data\
          --env-file /home/flatcar/.minio-forgejo/.env\
          quay.io/minio/minio server /data --console-address ":9001"
        [Install]
        WantedBy=multi-user.target
    - name: lldap-forgejo.service
      enabled: true
      contents: |
        [Unit]
        Description=run lldap
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service

        [Service]
        Type=oneshot
        RemainAfterExit=true
        WorkingDirectory=/home/flatcar
        User=lldap
        Group=lldap
        ExecStartPre=-/usr/bin/docker stop lldap-forgejo
        ExecStartPre=-/usr/bin/docker rm lldap-forgejo
        ExecStartPre=/usr/bin/docker pull harbor.honeblog.com/auth/lldap:stable
        ExecStart=/usr/bin/docker run --name lldap-forgejo\
          -p 3890:3890\
          -p 17170:17170\
          -v /home/flatcar/.lldap-forgejo/data:/data\
          --env-file /home/flatcar/.lldap-forgejo/.env\
          harbor.honeblog.com/auth/lldap:stable
        [Install]
        WantedBy=multi-user.target
storage:
  directories:
    - path: /home/flatcar/.forgejo/data
      user: { name: forgejo }
      group: { name: forgejo }
    - path: /home/flatcar/.postgres-forgejo/data
      user: { name: postgres }
      group: { name: postgres }
    - path: /home/flatcar/.minio-forgejo/data/forgejo
      user: { name: minio }
      group: { name: minio }
  files:
    - path: /etc/systemd/network/static.network
      contents:
        inline: |
          [Match]
          Name=eth0

          [Network]
          Address=172.20.20.1/16
          Gateway=172.20.0.1
          NTP=172.20.0.1
    - path: /etc/hostname
      contents:
        inline: git.honeblog.com
