variant: flatcar
version: 1.1.0
ignition:
  config:
    merge:
      - local: out/flatcar_base.json
passwd:
  users:
    - name: forgejo
      uid: 1500
      groups: [docker]
    - name: postgres
      groups: [docker]
    - name: minio
      groups: [docker]
    - name: lldap
      groups: [docker]
systemd:
  units:
    - name: forgejo.service
      enabled: false
      contents: |
        [Unit]
        Description=run forgejo
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service

        [Service]
        Type=simple
        Restart=always
        RestartSec=10
        WorkingDirectory=/home/flatcar
        User=forgejo
        Group=forgejo

        ExecStartPre=-/usr/bin/docker stop forgejo
        ExecStartPre=-/usr/bin/docker rm forgejo
        ExecStartPre=/usr/bin/docker pull harbor.reyokatsu.net/others/forgejo:10
        ExecStart=/usr/bin/docker run --rm --name forgejo\
          -v /home/flatcar/.forgejo/data:/data\
          -v /etc/timezone:/etc/timeozone:ro\
          -v /etc/localtime:/etc/localtime:ro\
          -p 3000:3000\
          -p 222:22\
          --env-file /home/flatcar/.forgejo/.env\
          harbor.reyokatsu.net/others/forgejo:10

        [Install]
        WantedBy=multi-user.target
    - name: postgres-forgejo.service
      enabled: false
      contents: |
        [Unit]
        Description=run postgres
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service

        [Service]
        Type=simple
        Restart=always
        RestartSec=10
        WorkingDirectory=/home/flatcar
        User=postgres
        Group=postgres

        ExecStartPre=-/usr/bin/docker stop postgres-forgejo
        ExecStartPre=-/usr/bin/docker rm postgres-forgejo
        ExecStartPre=/usr/bin/docker pull harbor.reyokatsu.net/database/postgres:17
        ExecStart=/usr/bin/docker run --rm --name postgres-forgejo\
          -v /home/flatcar/.postgres-forgejo/data:/var/lib/postgresql/data\
          -p 5432:5432\
          --env-file /home/flatcar/.postgres-forgejo/.env\
          harbor.reyokatsu.net/database/postgres:17

        [Install]
        WantedBy=multi-user.target
    - name: minio-forgejo.service
      enabled: false
      contents: |
        [Unit]
        Description=run minio
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service

        [Service]
        Type=simple
        Restart=always
        RestartSec=10
        WorkingDirectory=/home/flatcar
        User=minio
        Group=minio

        ExecStartPre=-/usr/bin/docker stop minio-forgejo
        ExecStartPre=-/usr/bin/docker rm minio-forgejo
        ExecStartPre=/usr/bin/docker pull quay.io/minio/minio
        ExecStart=/usr/bin/docker run --name minio-forgejo\
          -p 9000:9000 -p 9001:9001\
          -v /home/flatcar/.minio-forgejo/data:/data\
          --env-file /home/flatcar/.minio-forgejo/.env\
          quay.io/minio/minio server /data --console-address ":9001"

        [Install]
        WantedBy=multi-user.target
    - name: lldap-forgejo.service
      enabled: false
      contents: |
        [Unit]
        Description=run lldap
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service

        [Service]
        Type=simple
        Restart=always
        RestartSec=10
        WorkingDirectory=/home/flatcar
        User=lldap
        Group=lldap

        ExecStartPre=-/usr/bin/docker stop lldap-forgejo
        ExecStartPre=-/usr/bin/docker rm lldap-forgejo
        ExecStartPre=/usr/bin/docker pull harbor.reyokatsu.net/auth/lldap:stable
        ExecStart=/usr/bin/docker run --name lldap-forgejo\
          -p 3890:3890\
          -p 17170:17170\
          -v /home/flatcar/.lldap-forgejo/data:/data\
          --env-file /home/flatcar/.lldap-forgejo/.env\
          harbor.reyokatsu.net/auth/lldap:stable

        [Install]
        WantedBy=multi-user.target

storage:
  directories:
    - path: /home/flatcar/.forgejo/data
      user: { name: forgejo }
      group: { name: forgejo }
    - path: /home/flatcar/.postgres-forgejo/data
      user: { name: postgres }
      group: { name: postgres }
    - path: /home/flatcar/.minio-forgejo/data/forgejo
      user: { name: minio }
      group: { name: minio }
  files:
    - path: /etc/systemd/network/static.network
      contents:
        inline: |
          [Match]
          Name=eth0

          [Network]
          Address=172.20.20.1/16
          Gateway=172.20.0.1
          NTP=172.20.0.1
    - path: /etc/hostname
      contents:
        inline: git.reyokatsu.net
    - path: /home/flatcar/.forgejo/.env
      user: { name: forgejo }
      group: { name: forgejo }
      mode: 0600
      contents:
        inline: |
          USER_UID=1500
          USER_GID=1500
          FORGEJO__server_DOMAIN=git.reyokatsu.net
          FORGEJO__server_SSH_DOMAIN=git.reyokatsu.net
          FORGEJO__server_ROOT_URL=https://git.reyokatsu.net/
          FORGEJO__server_HTTP_PORT=3000
          FORGEJO__server_SSH_PORT=222
          FORGEJO__server_SSH_LISTEN_PORT=22
          FORGEJO__server_LFS_START_SERVER=true
          FORGEJO__database__DB_TYPE=postgres
          FORGEJO__database__HOST=172.20.20.1:5432
          FORGEJO__database__NAME=forgejo
          FORGEJO__database__USER=
          FORGEJO__database__PASSWD=
          FORGEJO__metrics__ENABLED=true
          FORGEJO__storage__STORAGE_TYPE=minio
          FORGEJO__storage__MINIO_ENDPOINT=172.20.20.1:9000
          FORGEJO__storage__MINIO_ACCESS_KEY_ID=
          FORGEJO__storage__MINIO_SECRET_ACCESS_KEY=
          FORGEJO__storage__MINIO_BUCKET=forgejo
    - path: /home/flatcar/.postgres-forgejo/.env
      user: { name: postgres }
      group: { name: postgres }
      mode: 0600
      contents:
        inline: |
          POSTGRES_USER=
          POSTGRES_PASSWORD=
          POSTGRES_DB=forgejo
          TZ="Asia/Tokyo"
    - path: /home/flatcar/.minio-forgejo/.env
      user: { name: minio }
      group: { name: minio }
      mode: 0600
      contents:
        inline: |
          MINIO_ROOT_USER=
          MINIO_ROOT_PASSWORD=
    - path: /home/flatcar/.lldap-forgejo/.env
      user: { name: lldap }
      group: { name: lldap }
      mode: 0600
      contents:
        inline: |
          TZ=Asia/Tokyo
          LLDAP_JWT_SECRET=
          LLDAP_KEY_SEED=
          LLDAP_LDAP_BASE_DN=dc=peach-ktq,dc=dev
          LLDAP_LDAP_USER_PASS=
