variant: flatcar
version: 1.1.0
ignition:
  config:
    merge:
      - local: out/flatcar_base.json

systemd:
  units:
    - name: systemd-sysupdate.timer
      enabled: true
    - name: systemd-sysupdate.service
      dropins:
        - name: docker_compose.conf
          contents: |
            [Service]
            ExecStartPre=/usr/bin/sh -c "readlink --canonicalize /etc/extensions/docker_compose.raw > /tmp/docker_compose"
            ExecStartPre=/usr/lib/systemd/systemd-sysupdate -C docker_compose update
            ExecStartPost=/usr/bin/sh -c "readlink --canonicalize /etc/extensions/docker_compose.raw > /tmp/docker_compose-new"
            ExecStartPost=/usr/bin/sh -c "if ! cmp --silent /tmp/docker_compose /tmp/docker_compose-new; then touch /run/reboot-required; fi"
    - name: init_harbor.service
      enabled: true
      contents: |
        [Unit]
        Description=Install Harbor
        Requires=systemd-sysupdate.service
        After=systemd-sysupdate.service
        
        [Service]
        Type=oneshot
        RemainAfterExit=true
        WorkingDirectory=/home/flatcar
        User=flatcar
        Group=flatcar
        ExecStartPre=-/usr/bin/mkdir /home/flatcar/.harbor/harbor_installer
        ExecStartPre=-/usr/bin/tar xzvf /home/flatcar/.harbor/harbor-online-installer.tgz -C /home/flatcar/.harbor/harbor_installer --strip-components 1
        ExecStart=/usr/bin/cp /home/flatcar/.harbor/harbor.yml /home/flatcar/.harbor/harbor_installer/harbor.yml

        [Install]
        WantedBy=multi-user.target

storage:
  directories:
    - path: /home/flatcar/.harbor
      user: {name: flatcar}
      group: {name: flatcar}
    - path: /home/flatcar/.harbor/certs
      overwrite: false
      user: {name: flatcar}
      group: {name: flatcar}
    - path: /home/flatcar/.harbor/data
      overwrite: false
      user: {id: 10000}
      group: {id: 10000}
    - path: /home/flatcar/.harbor/data/secret/core
      overwrite: false
      user: {id: 10000}
      group: {id: 10000}
    - path: /home/flatcar/.harbor/data/secret/registry
      overwrite: false
      user: {id: 10000}
      group: {id: 10000}
    - path: /home/flatcar/.harbor/data/secret/cert
      overwrite: false
      user: {id: 10000}
      group: {id: 10000}
    - path: /home/flatcar/.harbor/data/secret/keys/secretkey
      overwrite: false
      user: {id: 10000}
      group: {id: 10000}
    - path: /home/flatcar/.harbor/data/registry
      overwrite: false
      user: {id: 10000}
      group: {id: 10000}
      mode: 0700
    - path: /home/flatcar/.harbor/data/database/pg15
      overwrite: false
      user: {id: 999}
      group: {id: 999}
    - path: /home/flatcar/.harbor/data/redis
      overwrite: false
      user: {id: 999}
      group: {id: 999}
    - path: /etc/docker/certs.d/harbor.honeblog.com
      overwrite: false
      user: {name: root}
      group: {name: root}
  files:
    - path: /etc/systemd/network/static.network
      contents:
        inline: |
          [Match]
          Name=eth0

          [Network]
          Address=172.20.5.2/16
          Gateway=172.20.0.1
          NTP=172.20.0.1
    - path: /etc/hostname
      contents:
        inline: harbor.honeblog.com
    - path: /home/flatcar/.harbor/harbor-online-installer.tgz
      contents: 
        source: "https://github.com/goharbor/harbor/releases/download/v2.12.2/harbor-online-installer-v2.12.2.tgz"
      user: {name: flatcar}
      group: {name: flatcar}
    - path: /home/flatcar/.harbor/harbor.yml
      contents:
        local: config/flatcar_harbor/harbor.yml
      user: {name: flatcar}
      group: {name: flatcar}
    - path: /opt/extensions/docker_compose/docker_compose-2.24.5-x86-64.raw
      mode: 0644
      contents:
        source: https://github.com/flatcar/sysext-bakery/releases/download/latest/docker_compose-2.24.5-x86-64.raw
    - path: /etc/sysupdate.docker_compose.d/docker_compose.conf
      contents:
        source: https://github.com/flatcar/sysext-bakery/releases/download/latest/docker_compose.conf
    - path: /etc/sysupdate.d/noop.conf
      contents:
        source: https://github.com/flatcar/sysext-bakery/releases/download/latest/noop.conf
  links:
    - target: /opt/extensions/docker_compose/docker_compose-2.24.5-x86-64.raw
      path: /etc/extensions/docker_compose.raw
      hard: false
