variant: flatcar
version: 1.1.0
ignition:
  config:
    merge:
      - local: out/flatcar_base.json

systemd:
  units:
    - name: minio_loki.service
      enabled: true
      contents: |
        [Unit]
        Description=run MinIO of Loki
        Requires=docker.service
        After=docker.service

        [Service]
        Type=simple
        ExecStartPre=-/usr/bin/docker stop minio_loki
        ExecStartPre=-/usr/bin/docker rm minio_loki
        ExecStartPre=/usr/bin/docker pull quay.io/minio/minio
        ExecStart=/usr/bin/docker run --name minio_loki\
         --env-file /home/flatcar/K-Loki/minio_loki/.env\
         -p 9000:9000 -p 9001:9001\
         -v /home/flatcar/K-Loki/minio_loki/minio_data:/data\
         quay.io/minio/minio server /data --console-address ":9001"

        [Install]
        WantedBy=multi-user.target
    - name: loki.service
      enabled: true
      contents: |
        [Unit]
        Description=run Loki
        Requires=docker.service
        After=docker.service

        [Service]
        Type=simple
        ExecStartPre=-/usr/bin/docker stop loki
        ExecStartPre=-/usr/bin/docker rm loki
        ExecStartPre=/usr/bin/docker pull grafana/loki
        ExecStart=/usr/bin/docker run --name loki\
         --env-file /home/flatcar/K-Loki/minio_loki/.env\
         -p 3100:3100\
         -v /home/flatcar/K-Loki/loki/loki_config:/etc/loki\
         grafana/loki -config.expand-env=true -config.file=/etc/loki/config.yaml

        [Install]
        WantedBy=multi-user.target

storage:
  directories:
    - path: /home/flatcar/K-Loki/minio_loki/minio_data/loki
  files:
    - path: /etc/systemd/network/static.network
      contents:
        inline: |
          [Match]
          Name=eth0

          [Network]
          Address=172.20.5.15/16
          Gateway=172.20.0.1
          NTP=172.20.0.1
    - path: "/home/flatcar/K-Loki/loki/loki_config/config.yaml"
      contents:
        source: "https://raw.githubusercontent.com/Honekatsu/K-Loki/refs/heads/main/loki-config.yaml"
