variant: flatcar
version: 1.1.0
ignition:
  config:
    merge:
      - local: out/flatcar_net_base.json
storage:
  files:
    - path: /etc/systemd/network/static.network
      contents:
        inline: |
          [Match]
          Name=eth0

          [Network]
          Address=172.20.0.4/16
          Gateway=172.20.0.1
          NTP=172.20.0.1
    - path: /etc/hostname
      overwrite: true
      contents:
        inline: net01.reyokatsu.net
    - path: /home/flatcar/.coredns/config/Corefile
      user: { name: k-dns }
      group: { name: k-dns }
      contents:
        local: config/flatcar_net/coredns/Corefile01
