variant: flatcar
version: 1.1.0
ignition:
  config:
    merge:
      - local: out/flatcar_base.json
passwd:
  users:
    - name: k-dns
      groups: [docker]
    - name: k-traefik
      groups: [docker]
systemd:
  units:
    - name: coredns.service
      enabled: true
      contents: |
        [Unit]
        Description=run CoreDNS
        Requires=docker.service
        After=docker.service

        [Service]
        Type=simple
        User=k-dns
        Group=k-dns
        ExecStartPre=-/usr/bin/docker stop coredns
        ExecStartPre=-/usr/bin/docker rm coredns
        ExecStartPre=/usr/bin/docker pull coredns/coredns:latest
        ExecStart=/usr/bin/docker run --rm --name coredns\
          -v /home/flatcar/.coredns/config:/etc/coredns\
          -p 53:53 -p 53:53/udp -p 9153:9153\
          coredns/coredns -conf /etc/coredns/Corefile

        [Install]
        WantedBy=multi-user.target
    - name: traefik.service
      enabled: true
      contents: |
        [Unit]
        Description=run Traefik
        Requires=docker.service
        After=docker.service

        [Service]
        Type=simple
        User=k-traefik
        Group=k-traefik
        ExecStartPre=-/usr/bin/docker stop traefik
        ExecStartPre=-/usr/bin/docker rm traefik
        ExecStartPre=/usr/bin/docker pull traefik:latest
        ExecStart=/usr/bin/docker run --rm --name traefik\
          --env-file /home/flatcar/.traefik/.traefik.env\
          -v /home/flatcar/.traefik/config:/etc/traefik\
          -v /home/flatcar/.traefik/logs:/logs\
          -v /home/flatcar/.traefik/acme:/acme\
          -v /var/run/docker.sock:/var/run/docker.sock\
          -p 80:80 -p 443:443/tcp -p 8082:8082/tcp -p 8443:8443/tcp\
          -l traefik.enable=true\
          traefik:latest

        [Install]
        WantedBy=multi-user.target

storage:
  directories:
    - path: /home/flatcar/.traefik/logs
      user: { name: k-traefik }
      group: { name: k-traefik }
    - path: /home/flatcar/.traefik/acme
      user: { name: k-traefik }
      group: { name: k-traefik }
  files:
    - path: /etc/systemd/resolved.conf.d/10-DNS-override.conf
      overwrite: true
      contents:
        inline: |
          [Resolve]
          DNS=172.20.0.1
    # - path: /etc/sysconfig/iptables
    #   contents:
    #     inline: |
    - path: /etc/systemd/resolved.conf.d/stop_dns_stub_listener.conf
      contents:
        inline: |
          [Resolve]
          DNSStubListener=no
    - path: /home/flatcar/.traefik/config/traefik.yml
      user: { name: k-traefik }
      group: { name: k-traefik }
      contents:
        local: config/flatcar_net/traefik/traefik.yml
    - path: /home/flatcar/.traefik/config/external_service.yml
      user: { name: k-traefik }
      group: { name: k-traefik }
      contents:
        local: config/flatcar_net/traefik/external_service.yml
