variant: flatcar
version: 1.1.0
ignition:
  config:
    merge:
      - local: out/flatcar_base.json
passwd:
  users:
    - name: prometheus
      groups: [docker]
    - name: loki
      groups: [docker]
    - name: grafana
      groups: [docker]
systemd:
  units:
    - name: minio_loki.service
      enabled: true
      contents: |
        [Unit]
        Description=run MinIO of Loki
        Requires=docker.service
        After=docker.service

        [Service]
        Type=simple
        User=loki
        Group=loki
        ExecStartPre=-/usr/bin/docker stop minio_loki
        ExecStartPre=-/usr/bin/docker rm minio_loki
        ExecStartPre=/usr/bin/docker pull quay.io/minio/minio
        ExecStart=/usr/bin/docker run --name minio_loki\
         --env-file /home/flatcar/.loki/minio_loki/.env\
         -p 9000:9000 -p 9001:9001\
         -v /home/flatcar/.loki/minio_loki/minio_data:/data\
         quay.io/minio/minio server /data --console-address ":9001"

        [Install]
        WantedBy=multi-user.target
    - name: loki.service
      enabled: true
      contents: |
        [Unit]
        Description=run Loki
        Requires=docker.service
        After=docker.service

        [Service]
        Type=simple
        User=loki
        Group=loki
        ExecStartPre=-/usr/bin/docker stop loki
        ExecStartPre=-/usr/bin/docker rm loki
        ExecStartPre=/usr/bin/docker pull grafana/loki
        ExecStart=/usr/bin/docker run --name loki\
         --env-file /home/flatcar/.loki/minio_loki/.env\
         -p 3100:3100\
         -v /home/flatcar/.loki/loki/loki_config:/etc/loki\
         grafana/loki -config.expand-env=true -config.file=/etc/loki/config.yaml

        [Install]
        WantedBy=multi-user.target
    - name: prometheus.service
      enabled: true
      contents: |
        [Unit]
        Description=run Prometheus
        Requires=docker.service
        After=docker.service

        [Service]
        Type=simple
        WorkingDirectory=/home/flatcar
        User=prometheus
        Group=prometheus
        ExecStartPre=-/usr/bin/docker stop prometheus
        ExecStartPre=-/usr/bin/docker rm prometheus
        ExecStartPre=/usr/bin/docker pull harbor.reyokatsu.net/management/prometheus:latest
        ExecStartPre=-/usr/bin/sh /home/flatcar/.prometheus/create_config.sh
        ExecStart=/usr/bin/docker run --name prometheus\
         -p 9090:9090\
         -v /home/flatcar/.prometheus/config:/config\
         -v /home/flatcar/.prometheus/data:/prometheus\
         harbor.reyokatsu.net/management/prometheus:latest\
         --config.file=/config/prometheus.yml
        [Install]
        WantedBy=multi-user.target
    - name: grafana.service
      enabled: true
      contents: |
        [Unit]
        Description=run Grafana dashboard
        Requires=docker.service
        After=docker.service

        [Service]
        Type=simple
        WorkingDirectory=/home/flatcar
        User=grafana
        Group=grafana
        ExecStartPre=-/usr/bin/docker stop grafana
        ExecStartPre=-/usr/bin/docker rm grafana
        ExecStartPre=/usr/bin/docker pull harbor.reyokatsu.net/management/grafana-enterprise:latest
        ExecStart=/usr/bin/docker run --name grafana\
          -p 3000:3000\
          -v /home/flatcar/.grafana/data:/var/lib/grafana\
          harbor.reyokatsu.net/management/grafana-enterprise:latest
        [Install]
        WantedBy=multi-user.target

storage:
  directories:
    - path: /home/flatcar/.loki/minio_loki/minio_data/loki
    - path: /home/flatcar/.prometheus/data
      user: { id: 65534 }
      group: { id: 65534 }
      mode: 0700
    - path: /home/flatcar/.prometheus/config
      user: { name: prometheus }
      group: { name: prometheus }
    - path: /home/flatcar/.grafana/data
      user: { id: 472 }
      group: { id: 472 }
  files:
    - path: /etc/systemd/network/static.network
      contents:
        inline: |
          [Match]
          Name=eth0

          [Network]
          Address=172.20.5.15/16
          Gateway=172.20.0.1
          NTP=172.20.0.1
    - path: "/home/flatcar/.loki/loki/loki_config/config.yaml"
      user: { name: loki }
      group: { name: loki }
      contents:
        local: "config/flatcar_prometheus/loki/loki-config.yaml"
    - path: "/home/flatcar/.prometheus/create_config.sh"
      user: { name: prometheus }
      group: { name: prometheus }
      contents:
        local: "config/flatcar_prometheus/prometheus/create_config.sh"
    - path: "/home/flatcar/.prometheus/prometheus.yml.template"
      user: { name: prometheus }
      group: { name: prometheus }
      contents:
        local: "config/flatcar_prometheus/prometheus/prometheus.yml.template"
